### ISSUE TITLE
Crash w/ Mystic World

### ISSUE THREAD

**Issue by WenXin20** [MysticMods/MysticalLib#10]
Forge 14.23.5.2810-1.12.2
[Blockcraftery v1.2.0](https://minecraft.curseforge.com/projects/blockcraftery)
[Mystic World v1.0.1](https://minecraft.curseforge.com/projects/mystic-world)
Mystical Lib v1.1.1

I got this crash while trying to load the game with Blockcraftery and Mystic World mods.
[Crash Report](https://gist.github.com/WenXin20/b646454d5caa494181a5c5660ae09a08)

**Comment by EpicSquid** [comment]
Duh, I am an idiot. Its a mystic world issue. I will upload a new jar asap

**Comment by kreezxil** [comment]
well this is pointless then,

Issue:  1.12.2-1.1.1 crashes dedicated server Forge 1.12.2 build 2815

Notes:
     class not found

crash report:
http://paste.ubuntu.com/p/3PpdZBzSDt/

fml server latest:
http://paste.ubuntu.com/p/9NxjDF3qSp/

**Comment by EpicSquid** [comment]
Yes I know the bug and have a fix available, I just have not had a chance to upload it yet. I will do so as soon as I can

**Comment by EpicSquid** [comment]
Fixed, new version (1.2.0) of Mystic World uploading now

**Comment by ghost** [comment]
Minecraft crashes when I add the mystical world mod.

My mod pack is in 1.12.2, the versions of the mod that I tried were: 1.2.0; 1.4.0; 1.6.1

Crash Report:
https://www.mediafire.com/file/z6h4xaheamn0a97/crash-2020-01-09_19.30.34-client.txt/file

**Comment by noobanidus** [comment]
Update MysticalLib, version 1.3.1 is quite old. Please open new tickets in the future, as this is an old and unrelated topic.

**Comment by ghost** [comment]
Thank you, but it still crashes... I used the latest version: 1.4.0

**Comment by ghost** [comment]
Here's the report:
https://www.mediafire.com/file/5v97h0vjpbc1vnu/crash-2020-01-09_23.04.36-client.txt/file

**Comment by noobanidus** [comment]
When in doubt, check all versions: 

Roots is 3.0.4 which is *ancient*. Please update to 3.0.21.
Mystical World is 1.4.4, also quite old. Please update to 1.6.1.

**Comment by ghost** [comment]
Thanks a lot! This is my first mod pack so ig I'm starting. Roots is a very interesting mod, very good work.
